steps:
  - id: run-terraform-apply
    name: 'gcr.io/oss-terraform-jinghanma/terraform'
    env:
      - "PROJECT_ID=oss-terraform-jinghanma"
    script: |
      #!/bin/bash
      set -e
      terraform plan
      terraform apply
