steps:
  - id: run-terraform-apply
    name: "gcr.io/cloud-builders/gcloud"
    env:
      - "PROJECT_ID=oss-terraform-jinghanma"
    script: |
      #!/bin/bash
      set -e
      terraform plan
      terraform apply
