steps:
  - id: run-terraform-apply
    name: 'centos'
    env:
      - "PROJECT_ID=oss-terraform-jinghanma"
    script: |
      #!/bin/bash
      set -e
      sudo yum install -y yum-utils
      sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      sudo yum -y install terraform
      terraform plan
      terraform apply
